import dynamic from "next/dynamic";
import { type Processes } from "contexts/process/types";
import {
  BASE_PATH,
  FOLDER_ICON,
  ICON_PATH,
  TASKBAR_HEIGHT,
} from "utils/constants";

const directory: Processes = {
  BoxedWine: {
    allowResizing: false,
    backgroundColor: "#000",
    Component: dynamic(() => import("components/apps/BoxedWine")),
    defaultSize: {
      height: 480,
      width: 640,
    },
    dependantLibs: [`${BASE_PATH}/Program Files/BoxedWine/boxedwine.wasm`],
    icon: `${ICON_PATH}/boxedwine.webp`,
    libs: [
      `${BASE_PATH}/Program Files/BoxedWine/browserfs.boxedwine.js`,
      `${BASE_PATH}/Program Files/BoxedWine/boxedwine-shell.js`,
      `${BASE_PATH}/Program Files/BoxedWine/boxedwine.js`,
    ],
    lockAspectRatio: true,
    singleton: true,
    title: "BoxedWine",
  },
  Browser: {
    backgroundColor: "#FFF",
    Component: dynamic(() => import("components/apps/Browser")),
    defaultSize: {
      height: 500,
      width: 600,
    },
    icon: `${ICON_PATH}/chromium.webp`,
    title: "Browser",
  },
  Chess: {
    backgroundColor: "#312E2B",
    Component: dynamic(() => import("components/apps/Chess")),
    defaultSize: {
      height: 567,
      width: 420,
    },
    icon: `${ICON_PATH}/chess.webp`,
    libs: [`${BASE_PATH}/Program Files/Chess/chessboard2.min.css`],
    title: "Chess",
  },
  ClassiCube: {
    backgroundColor: "#201E20",
    Component: dynamic(() => import("components/apps/ClassiCube")),
    defaultSize: {
      height: 420,
      width: 640,
    },
    icon: `${ICON_PATH}/classicube.webp`,
    libs: [`${BASE_PATH}/Program Files/ClassiCube/ClassiCube.js`],
    title: "ClassiCube",
  },
  DevTools: {
    backgroundColor: "#242424",
    Component: dynamic(() => import("components/apps/DevTools")),
    defaultSize: {
      height: 380,
      width: 545,
    },
    icon: `${ICON_PATH}/eruda.webp`,
    libs: [
      `${BASE_PATH}/Program Files/Eruda/eruda.js`,
      `${BASE_PATH}/Program Files/Eruda/eruda-monitor.js`,
    ],
    singleton: true,
    title: "DevTools",
  },
  DXBall: {
    backgroundColor: "#000",
    Component: dynamic(() => import("components/apps/DX-Ball")),
    icon: `${ICON_PATH}/dxball.webp`,
    libs: [`${BASE_PATH}/Program Files/DX-Ball/game.js`],
    lockAspectRatio: true,
    singleton: true,
    title: "DX-Ball",
  },
  Emulator: {
    backgroundColor: "#000",
    Component: dynamic(() => import("components/apps/Emulator")),
    defaultSize: {
      height: 400,
      width: 600,
    },
    dependantLibs: [
      `${BASE_PATH}/Program Files/EmulatorJs/emu-css.min.css`,
      `${BASE_PATH}/Program Files/EmulatorJs/emulator.min.js`,
    ],
    icon: `${ICON_PATH}/emulator.webp`,
    libs: [`${BASE_PATH}/Program Files/EmulatorJs/loader.js`],
    lockAspectRatio: true,
    title: "Emulator",
  },
  FileExplorer: {
    backgroundColor: "#202020",
    Component: dynamic(() => import("components/apps/FileExplorer")),
    defaultSize: {
      height: 325,
      width: 447,
    },
    icon: FOLDER_ICON,
    title: "File Explorer",
  },
  IRC: {
    backgroundColor: "#FFF",
    Component: dynamic(() => import("components/apps/IRC")),
    defaultSize: {
      height: 512,
      width: 704,
    },
    icon: `${ICON_PATH}/kiwiirc.webp`,
    libs: [`${BASE_PATH}/Program Files/kiwiirc/index.html`],
    title: "IRC",
  },
  JSDOS: {
    autoSizing: true,
    backgroundColor: "#000",
    Component: dynamic(() => import("components/apps/JSDOS")),
    defaultSize: {
      height: 200,
      width: 320,
    },
    dependantLibs: [`${BASE_PATH}/Program Files/js-dos/wdosbox.wasm`],
    icon: `${ICON_PATH}/jsdos.webp`,
    libs: [
      `${BASE_PATH}/Program Files/js-dos/emulators.js`,
      `${BASE_PATH}/Program Files/js-dos/emulators-ui.js`,
    ],
    lockAspectRatio: true,
    title: "js-dos v7",
  },
  Marked: {
    backgroundColor: "#FFF",
    Component: dynamic(() => import("components/apps/Marked")),
    defaultSize: {
      height: 480,
      width: 560,
    },
    icon: `${ICON_PATH}/marked.webp`,
    libs: [
      `${BASE_PATH}/Program Files/Marked/marked.min.js`,
      `${BASE_PATH}/Program Files/Marked/purify.min.js`,
    ],
    title: "Marked",
  },
  Messenger: {
    backgroundColor: "#242526",
    Component: dynamic(() => import("components/apps/Messenger")),
    defaultSize: {
      height: 500,
      width: 425,
    },
    icon: `${ICON_PATH}/messenger.webp`,
    singleton: true,
    title: "Messenger",
  },
  MonacoEditor: {
    backgroundColor: "#1E1E1E",
    Component: dynamic(() => import("components/apps/MonacoEditor")),
    defaultSize: {
      height: 480,
      width: 544,
    },
    dependantLibs: [
      `${BASE_PATH}/Program Files/MonacoEditor/vs/loader.js`,
      `${BASE_PATH}/Program Files/MonacoEditor/vs/editor/editor.main.js`,
      `${BASE_PATH}/Program Files/MonacoEditor/vs/editor/editor.main.css`,
      `${BASE_PATH}/Program Files/MonacoEditor/vs/editor/editor.main.nls.js`,
    ],
    icon: `${ICON_PATH}/monaco.webp`,
    title: "Monaco Editor",
  },
  OpenType: {
    backgroundColor: "#FFF",
    Component: dynamic(() => import("components/apps/OpenType")),
    icon: `${ICON_PATH}/opentype.webp`,
    preferProcessIcon: true,
    title: "OpenType",
  },
  OpenWith: {
    allowResizing: false,
    backgroundColor: "#FFF",
    Component: dynamic(() => import("components/system/Dialogs/OpenWith")),
    defaultSize: {
      height: 492,
      width: 392,
    },
    dialogProcess: true,
    hideTaskbarEntry: true,
    hideTitlebar: true,
    icon: `${ICON_PATH}/unknown.webp`,
    title: "Open With",
  },
  Paint: {
    backgroundColor: "#808080",
    Component: dynamic(() => import("components/apps/Paint")),
    icon: `${ICON_PATH}/paint.webp`,
    libs: [`${BASE_PATH}/Program Files/jspaint/index.html`],
    title: "Paint",
  },
  PDF: {
    backgroundColor: "#525659",
    Component: dynamic(() => import("components/apps/PDF")),
    icon: `${ICON_PATH}/pdf.webp`,
    libs: [`${BASE_PATH}/Program Files/PDF.js/pdf.js`],
    title: "PDF",
  },
  Photos: {
    backgroundColor: "#222",
    Component: dynamic(() => import("components/apps/Photos")),
    defaultSize: {
      height: 432,
      width: 576,
    },
    hideTitlebarIcon: true,
    icon: `${ICON_PATH}/photos.webp`,
    title: "Photos",
  },
  Properties: {
    allowResizing: false,
    backgroundColor: "rgb(240, 240, 240)",
    Component: dynamic(() => import("components/system/Dialogs/Properties")),
    defaultSize: {
      height: 412,
      width: 361,
    },
    dialogProcess: true,
    hideMaximizeButton: true,
    hideMinimizeButton: true,
    icon: "",
    title: "Properties",
  },
  Quake3: {
    backgroundColor: "#000",
    Component: dynamic(() => import("components/apps/Quake3")),
    defaultSize: {
      height: 480,
      width: 640,
    },
    icon: `${ICON_PATH}/quake3.webp`,
    libs: [`${BASE_PATH}/Program Files/Quake3/Quake3Game.js`],
    lockAspectRatio: true,
    title: "Quake III Arena",
  },
  Ruffle: {
    backgroundColor: "#000",
    Component: dynamic(() => import("components/apps/Ruffle")),
    defaultSize: {
      height: 400,
      width: 550,
    },
    icon: `${ICON_PATH}/ruffle.webp`,
    libs: [`${BASE_PATH}/Program Files/Ruffle/ruffle.js`],
    lockAspectRatio: true,
    title: "Ruffle",
  },
  Run: {
    allowResizing: false,
    Component: dynamic(() => import("components/system/Dialogs/Run")),
    defaultSize: {
      height: 174,
      width: 397,
    },
    dialogProcess: true,
    hideMaximizeButton: true,
    hideMinimizeButton: true,
    icon: `${ICON_PATH}/run.webp`,
    initialRelativePosition: {
      bottom: TASKBAR_HEIGHT + 11,
      left: 15,
    },
    singleton: true,
    title: "Run",
  },
  ScreenSaver: {
    allowResizing: false,
    Component: dynamic(() => import("components/system/Dialogs/ScreenSaver")),
    dialogProcess: true,
    hasWindow: false,
    hideTaskbarEntry: true,
    icon: `${ICON_PATH}/screensaver.webp`,
    singleton: true,
    title: "Screen Saver",
  },
  SpaceCadet: {
    backgroundColor: "#000",
    Component: dynamic(() => import("components/apps/SpaceCadet")),
    defaultSize: {
      height: 428,
      width: 600,
    },
    dependantLibs: [
      `${BASE_PATH}/Program Files/SpaceCadet/SpaceCadetPinball.wasm`,
    ],
    icon: `${ICON_PATH}/pinball.webp`,
    libs: [`${BASE_PATH}/Program Files/SpaceCadet/SpaceCadetPinball.js`],
    lockAspectRatio: true,
    title: "Space Cadet",
  },
  StableDiffusion: {
    backgroundColor: "rgb(235, 251, 247)",
    Component: dynamic(() => import("components/apps/StableDiffusion")),
    defaultSize: {
      height: 644,
      width: 538,
    },
    icon: `${ICON_PATH}/stablediffusion.webp`,
    singleton: true,
    title: "Stable Diffusion",
  },
  Terminal: {
    Component: dynamic(() => import("components/apps/Terminal")),
    backgroundColor: "#0C0C0C",
    defaultSize: {
      height: 370,
      width: 610,
    },
    icon: `${ICON_PATH}/xterm.webp`,
    title: "Terminal",
  },
  Tic80: {
    backgroundColor: "#1A1C2C",
    Component: dynamic(() => import("components/apps/Tic80")),
    defaultSize: {
      height: 480,
      width: 640,
    },
    icon: `${ICON_PATH}/tic80.webp`,
    libs: [`${BASE_PATH}/Program Files/Tic80/tic80.js`],
    lockAspectRatio: true,
    title: "TIC-80",
  },
  TinyMCE: {
    Component: dynamic(() => import("components/apps/TinyMCE")),
    backgroundColor: "#FFF",
    defaultSize: {
      height: 480,
      width: 640,
    },
    icon: `${ICON_PATH}/tinymce.webp`,
    libs: [`${BASE_PATH}/Program Files/TinyMCE/tinymce.min.js`],
    title: "TinyMCE",
  },
  Transfer: {
    allowResizing: false,
    backgroundColor: "#FFF",
    Component: dynamic(() => import("components/system/Dialogs/Transfer")),
    defaultSize: {
      height: 161,
      width: 400,
    },
    dialogProcess: true,
    icon: `${ICON_PATH}/copying.webp`,
    title: "Copying...",
  },
  V86: {
    allowResizing: false,
    backgroundColor: "#000",
    Component: dynamic(() => import("components/apps/V86")),
    defaultSize: {
      height: 400,
      width: 640,
    },
    icon: `${ICON_PATH}/v86.webp`,
    libs: [`${BASE_PATH}/Program Files/Virtual86/libv86.js`],
    lockAspectRatio: true,
    title: "Virtual x86",
  },
  VideoPlayer: {
    backgroundColor: "#000",
    Component: dynamic(() => import("components/apps/VideoPlayer")),
    defaultSize: {
      height: 480,
      width: 640,
    },
    icon: `${ICON_PATH}/vlc.webp`,
    libs: [`${BASE_PATH}/Program Files/Video.js/video.min.js`],
    title: "Video Player",
  },
  Webamp: {
    allowResizing: false,
    Component: dynamic(() => import("components/apps/Webamp")),
    hasWindow: false,
    icon: `${ICON_PATH}/webamp.webp`,
    libs: [`${BASE_PATH}/Program Files/Webamp/webamp.bundle.min.js`],
    singleton: true,
    title: "Webamp",
  },
};

export default directory;
